# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Number Baseball' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Number Baseball
  pod 'GoogleSignIn'

  target 'Number BaseballTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Number BaseballUITests' do
    # Pods for testing
  end

end
